#!/bin/bash

# Set the path to MinGW bin directory
export PATH=/usr/bin/x86_64-w64-mingw32:$PATH

# Set the path to MinGW include directory
MINGW_INCLUDE_PATH=/usr/x86_64-w64-mingw32/include

# Compile for Windows
x86_64-w64-mingw32-g++ -o engine.exe \
    -I$MINGW_INCLUDE_PATH \
    Source.cpp \
    Renderer.cpp \
    VertexBuffer.cpp \
    IndexBuffer.cpp \
    VertexBufferLayout.cpp \
    VertexArray.cpp \
    Shader.cpp \
    src/vendor/stb_image/stb_image.cpp \
    src/Texture.cpp \
    imgui_draw.cpp \
    imgui.cpp \
    imgui_tables.cpp \
    imgui_widgets.cpp \
    imgui_impl_glfw.cpp \
    CubeCollider.cpp \
    imgui_impl_opengl3.cpp \
    imgui_stdlib.cpp \
    -lglew32 -lglfw3 -lopengl32 -lgdi32 -luser32 -lkernel32 -lmingw32
